services:
  node:
    build: ./node/
    volumes:
      - ./node/app:/app
      - "${TIMELINES_DIR}:/app/volumes/timelines"
    environment:
      STEAM_API_KEY: ${STEAM_API_KEY}
      GIT_TOKEN: ${GIT_TOKEN}
